name: Carila
favicon: null
layout_spectrum: 0.8305387396831065
typography_spectrum: 0.6199929872527719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12353055900894105
  lightness: 0.2519575187470764
  saturation: 0.9739008522592485
  rhythmicContrast: 0.0026396799366921186
purpose: []
