name: Carila
favicon: null
layout_spectrum: 0.8305387396831065
typography_spectrum: 0.6199929872527719
title: Cari’s Personal Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c0ca8d'
    - '#7f8e2f'
    - '#6a6a6a'
    - '#404040'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
